name: templete_application
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^3.31.2
  slang_flutter: ^3.31.0

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  signals: ^5.5.0
  go_router: ^14.2.7
  skeletonizer: ^1.4.2
  flutter_gen: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.11
  slang_build_runner: ^3.31.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  go_router_builder: ^2.7.1

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:

  uses-material-design: true
# ここに slang の設定を追加
  assets:
    - assets/orechen.png
slang:
  base_locale: ja
  fallback_strategy: base_locale
  input_directory: i18n
  output_directory: lib/gen
  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
